language: node_js
node_js:
  - "10"
after_success:
  - yarn build
before_deploy:
  - cd ./lib
deploy:
  provider: heroku
  api_key:
    secure: m9jGGtBCqKmtbAEQ7psSk4Dhq71LC3gkfGlJTFbbEwPGpYZc8SDLGOR7/NI1MainHlq78vONje+DYlQ3nR8yQN7XA1FYpaktFmnofccr3xWBHf/uffswj9m//iCLLgUSVHEBQI28WrqStvgUgI4EIXLzaVgs+cr1UKDm1FAbNYrNz+JQ5zSMks5rzkwMvNxgiUwfv/yiDmEgnmXL8ilRrRhsI+fkAoxyQ6R92yF+Y5B0qNbiFbHJfB3eZWGLs7KsfDl02aJFSo+fNoREquogB3LSlyE8FigdsfKD6pkhzOBtYaOgiBSTg2YAYujXYihpTqeTNpGxTk1/MmNGvid01GgvE7xMTMR3PtUTnJ03fmR7NPnKMP+YhXnaWPDzv/nf1WNZHaTydQKNC0jD312R3I6/+9PVvHF6EnofbLg1Kbdeuq5benGjb+vOg/Q2gdRPSqqmKYJPaLXtVUlNKWbwTOgbxjyyVGH/dKpX0+Ph1ZRlza7Jt0Mec/RFTYT5Qias8LexJoB2adMEuwYgF+Los4vR0Ff5xS8YkEnLDNorSNMRlcTgwuZtWEjymCfq1hZzhpXzREKcgJwjtJJiXO1oUn1EzoFYq4SqYa59xGCaSYbpmYgCIh8OsPturrglntOGv3iEePRjW+45AoLlz7sW4T4rb/0PX+04WM33kAIfgdE=
  app: alfred
  skip_cleanup: true
  on:
    repo: jgretz/alfred
