language: node_js
node_js:
  - "10"
after_success:
  - yarn build
before_deploy:
  - cd ./lib
deploy:
  provider: heroku
  api_key:
    secure: IfKY1ZCg8aaHnStxfnJEpMpldOy1YwSDFIGFmDufEjnS8udMI6B9iK0tSgHQ+OeQHu1wdxi7gykMuSTd3+/Om0t3DI0cWOvK427m8SbIdcr5Y0e+Q86ISpvOuYA+ECci93ntcIl7RAjIGjF3vn6t4S+Eluvaa5mvl+ndpgZNS39uiJnnDIWwpTKRSG2/9fauNLJw26HQV8juEyrF7a7rMQNy3FWyGiTe3vVZEVnLqQnblzVTazYDNzLVEoik9nsWjW9424MGyhXeMJ5k3rDvbUkuf/w4FRcS50X5fcJQtOr90y8bF/6VgjwmmBgOEn0kwvu+zqJRoEGORoOlUVtFEMd+1TWwqCzqpTWIA/vxz0jFYFXzzjsODMTBqFzPpGHuCJJjjXRwWwAD6TzTdj1wWfXnWVNwvDx36qT9eIYPBCVRNP7kn3vK1K55MImGWwifj/7XWDrgqT/BUotv/oivO73gmspA57JqG3G4aVd8RH/EQlpihIYGfuuOnurYNTPVO4yzGz79Kb1cKvM6vMOU9cIsilQ4jMxsdmwwxmqRe4mGDNG/DBLH+/c2v0U7inuDTDQOEdkuw0jUB1JcRJBJEYBj4HwcKE8m6OkRpZ7PsRtwBUFH6vYAdddQvkwsxWeJTcvLXvZ0nevYLS32JQMHz6UQeHyfbYYctvPk5gT8IDk=
  app: alfred-gretz
  skip_cleanup: true
  on:
    repo: jgretz/alfred
