language: node_js
node_js:
- '10'
after_success:
- yarn build
before_deploy:
- cd ./lib
deploy:
  provider: heroku
  api_key:
    secure: R5UhO45dnVUUpNOfQfRL0dt/avqfgi5P38kQswWE4h6nHcpsP5PszPMrgXgGDdVcMU2Xqic+15/s/cQJiV0ufGvos194qcH4gw/rVYZ2TUHBDfDfUJgMvVhWDvODoO4z/94CEP9PUmAVTsOd3DGnzfl9lrmiXl/kwkiuooR93HXnkti+/lobrIPZJBGkugqTIh0neN2BD+jjeo35nMQGzrkEuSUcuMsQFpK0k+td4BmvMdo7D4jfkfuE8oZDq1OJu4wGIakpNAwASAfb0YRfuLQ0Afsg8xqUMq+N43iKNybGZM2Bjy2VmL3eTuu0Vbkp9gRDH1Ocxn5L63vo2uXdGjCfmvEpX25gmOZdaCBH1pdDtGmQEL9PBZIPgDY0VBNwh7CZrTuZ6MFiFAbuNvoR2UcBQJ87wdWJdwt39eJmsQLVGeeSjkbR92fmtFF5hjrnHFkdY7sbN0Uis15AW9GI92WOAhTCYqUwsUSCxjHySFwfHAGIabfoe/3FpuNSExvjcS3ogTv2vw8mPqeQ8mM1ad6mCvon3eXWIZ0FgJehTze0+LDQZjU8u6tHPhNv4nsie0dnwkY3I0ETNvRdaFlPcCq5AM014EXfQ1IBV6VyGxRxQ4g9O1I4lmytI3zH0nUsDZ4yysjYXl8ALsUxA+RNQhCWmthwjHYRkd/gywieeEg=
  app: alfred
  skip_cleanup: true
  on:
    repo: jgretz/alfred
